#!/bin/bash -l
#SBATCH -J hifiasm_triobinning
#SBATCH --output=hifiasm_triobinning-%j.output
#SBATCH --error=hifiasm_triobinning-%j.error
#SBATCH -t 240:00:00
#SBATCH --partition=bmh
#SBATCH --mail-type=ALL
#SBATCH --mail-user=plunarodriguez@ucdavis.edu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=100G

set -euo pipefail

echo "Starting at: $(date)"

#Files and directories
MAT=/group/gmonroegrp2/chaehee/Pablo/pistacia/HiFi_reads/Patl.fastq.gz
PAT=/group/gmonroegrp2/chaehee/Pablo/pistacia/HiFi_reads/Pint.fastq.gz
SAMPLE=/group/gmonroegrp2/chaehee/Pablo/pistacia/HiFi_reads/UCB1.fastq.gz

# Extract sample name from read file (handles .fastq.gz, .fq.gz, .fastq, .fq)
SAMPLE_NAME=$(basename "$SAMPLE")
SAMPLE_NAME=${SAMPLE_NAME%.fastq.gz}
SAMPLE_NAME=${SAMPLE_NAME%.fq.gz}
SAMPLE_NAME=${SAMPLE_NAME%.fastq}
SAMPLE_NAME=${SAMPLE_NAME%.fq}

OUT_DIR=/group/gmonroegrp2/chaehee/Pablo/UCB1_hybridization/04_genome_assembly_triobinning
mkdir -p "$OUT_DIR"
OUT_DIR01="${OUT_DIR}/01_raw_assembly_triobinning"
mkdir -p "$OUT_DIR01"
OUT="${OUT_DIR01}/hifiasm_triobinning/${SAMPLE_NAME}_triobinning_raw_assembly"

#You need yak, if you dont have it run this in your home directory

#cd ~
#git clone https://github.com/lh3/yak
#cd yak && make

#Then let's count kmers with yak, this will be used for the trio binning, you have to do it for each parental sample
#It does not matter if you have long or short reads

cd /home/plunarod/yak

./yak count -k31 -b37 -t64 -o $OUT_DIR01/Pint.yak $PAT
./yak count -k31 -b37 -t64 -o $OUT_DIR01/Patl.yak $MAT

source /home/plunarod/miniconda3/bin/activate
conda activate genome_assembly_env

#--h-cov is because of kcov result from genomescope
#--telo-m is the hightly conserved motif in flowering plants
#-l 0 is to not remove any duplicated regions, this is important in plants due to repetitive regions

hifiasm -o "${OUT}" -t 64 -1 $OUT_DIR01/Pint.yak -2 $OUT_DIR01/Patl.yak "$SAMPLE" --hom-cov ? -l 0 --telo-m CCCTAAA

#Convert gfa files to .fasta files for next alignments
awk '/^S/{print ">"$2"\n"$3}' "${OUT}.dip.hap1.p_ctg.gfa" > "${OUT}.hap1.fasta"
awk '/^S/{print ">"$2"\n"$3}' "${OUT}.dip.hap2.p_ctg.gfa" > "${OUT}.hap2.fasta"

echo "Finished at: $(date)"
